"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-04 21:27:33.314564
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_cache',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_ai_cache'))
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('default_margin', sa.Float(), nullable=True),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('icon', sa.String(length=32), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name=op.f('fk_categories_parent_id_categories'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories'))
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_parent_id'), ['parent_id'], unique=False)

    op.create_table('counters',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_counters'))
    )
    op.create_table('currencies',
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=8), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('is_base', sa.Boolean(), nullable=False),
    sa.Column('decimals', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_currencies'))
    )
    op.create_table('expense_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expense_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_expense_categories_name'))
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('entity', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('dedupe_key', sa.String(length=128), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    sa.UniqueConstraint('dedupe_key', name=op.f('uq_notifications_dedupe_key'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_kind'), ['kind'], unique=False)

    op.create_table('price_tiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('default_margin', sa.Float(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_tiers')),
    sa.UniqueConstraint('name', name=op.f('uq_price_tiers_name'))
    )
    op.create_table('saved_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_reports'))
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_settings'))
    )
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('address', sa.String(length=256), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('commission_rate', sa.Float(), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('location', sa.String(length=256), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_warehouses')),
    sa.UniqueConstraint('name', name=op.f('uq_warehouses_name'))
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('custom_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('field_type', sa.String(length=16), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('default_value', sa.String(length=256), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('visible_to_users', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_custom_fields_category_id_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_custom_fields')),
    sa.UniqueConstraint('key', name=op.f('uq_custom_fields_key'))
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('address', sa.String(length=256), nullable=False),
    sa.Column('tier_id', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('credit_limit', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tier_id'], ['price_tiers.id'], name=op.f('fk_customers_tier_id_price_tiers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers'))
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_phone'), ['phone'], unique=False)

    op.create_table('device_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('device_name', sa.String(length=128), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_device_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_sessions'))
    )
    with op.batch_alter_table('device_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_sessions_jti'), ['jti'], unique=True)
        batch_op.create_index(batch_op.f('ix_device_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('exchange_rate_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_code', sa.String(length=8), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], name=op.f('fk_exchange_rate_history_currency_code_currencies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_exchange_rate_history_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exchange_rate_history'))
    )
    with op.batch_alter_table('exchange_rate_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exchange_rate_history_currency_code'), ['currency_code'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('variant_attrs', sa.JSON(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('barcode', sa.String(length=64), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('brand', sa.String(length=128), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('cost_price', sa.Float(), nullable=False),
    sa.Column('margin', sa.Float(), nullable=True),
    sa.Column('price_locked', sa.Boolean(), nullable=False),
    sa.Column('sale_price', sa.Float(), nullable=False),
    sa.Column('min_stock', sa.Float(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('specs', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('track_expiry', sa.Boolean(), nullable=False),
    sa.Column('last_sold_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_products_category_id_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['products.id'], name=op.f('fk_products_parent_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_products_supplier_id_suppliers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_barcode'), ['barcode'], unique=True)
        batch_op.create_index(batch_op.f('ix_products_brand'), ['brand'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_products_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_parent_id'), ['parent_id'], unique=False)

    op.create_table('purchase_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('supplier_ref', sa.String(length=64), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('paid', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_purchase_invoices_supplier_id_suppliers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_purchase_invoices_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_purchase_invoices_warehouse_id_warehouses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_invoices')),
    sa.UniqueConstraint('number', name=op.f('uq_purchase_invoices_number'))
    )
    op.create_table('shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('opening_cash', sa.Float(), nullable=False),
    sa.Column('expected_cash', sa.Float(), nullable=False),
    sa.Column('actual_cash', sa.Float(), nullable=False),
    sa.Column('difference', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_shifts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shifts'))
    )
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shifts_user_id'), ['user_id'], unique=False)

    op.create_table('stock_counts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_stock_counts_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_stock_counts_warehouse_id_warehouses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_counts'))
    )
    op.create_table('sync_log',
    sa.Column('client_op_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sync_log_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('client_op_id', name=op.f('pk_sync_log'))
    )
    op.create_table('transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_warehouse_id', sa.Integer(), nullable=False),
    sa.Column('to_warehouse_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_warehouse_id'], ['warehouses.id'], name=op.f('fk_transfers_from_warehouse_id_warehouses')),
    sa.ForeignKeyConstraint(['to_warehouse_id'], ['warehouses.id'], name=op.f('fk_transfers_to_warehouse_id_warehouses')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_transfers_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transfers'))
    )
    op.create_table('batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('batch_no', sa.String(length=64), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_batches_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_batches_warehouse_id_warehouses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_batches'))
    )
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batches_expiry_date'), ['expiry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_batches_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_batches_warehouse_id'), ['warehouse_id'], unique=False)

    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('paid_from_cash', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['expense_categories.id'], name=op.f('fk_expenses_category_id_expense_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name=op.f('fk_expenses_shift_id_shifts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_expenses_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expenses'))
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenses_expense_date'), ['expense_date'], unique=False)

    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('customer_name', sa.String(length=128), nullable=False),
    sa.Column('customer_phone', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('tier_id', sa.Integer(), nullable=True),
    sa.Column('currency_code', sa.String(length=8), nullable=False),
    sa.Column('exchange_rate', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('discount', sa.Float(), nullable=False),
    sa.Column('tax_rate', sa.Float(), nullable=False),
    sa.Column('tax_amount', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('paid', sa.Float(), nullable=False),
    sa.Column('cost_total', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('original_invoice_id', sa.Integer(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_invoices_customer_id_customers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['original_invoice_id'], ['invoices.id'], name=op.f('fk_invoices_original_invoice_id_invoices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name=op.f('fk_invoices_shift_id_shifts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tier_id'], ['price_tiers.id'], name=op.f('fk_invoices_tier_id_price_tiers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_invoices_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_invoices_warehouse_id_warehouses'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices'))
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_number'), ['number'], unique=True)

    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('old_cost', sa.Float(), nullable=False),
    sa.Column('new_cost', sa.Float(), nullable=False),
    sa.Column('old_price', sa.Float(), nullable=False),
    sa.Column('new_price', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_price_history_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_price_history_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_history'))
    )
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_history_changed_at'), ['changed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_history_product_id'), ['product_id'], unique=False)

    op.create_table('product_field_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['custom_fields.id'], name=op.f('fk_product_field_values_field_id_custom_fields'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_field_values_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_field_values')),
    sa.UniqueConstraint('product_id', 'field_id', name=op.f('uq_product_field_values_product_id'))
    )
    with op.batch_alter_table('product_field_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_field_values_field_id'), ['field_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_field_values_product_id'), ['product_id'], unique=False)

    op.create_table('product_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_images_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_images'))
    )
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_images_product_id'), ['product_id'], unique=False)

    op.create_table('product_tier_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('tier_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_tier_prices_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tier_id'], ['price_tiers.id'], name=op.f('fk_product_tier_prices_tier_id_price_tiers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_tier_prices')),
    sa.UniqueConstraint('product_id', 'tier_id', name=op.f('uq_product_tier_prices_product_id'))
    )
    with op.batch_alter_table('product_tier_prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_tier_prices_product_id'), ['product_id'], unique=False)

    op.create_table('promotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('percent', sa.Float(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_promotions_category_id_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_promotions_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promotions'))
    )
    op.create_table('purchase_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('batch_no', sa.String(length=64), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_purchase_items_product_id_products')),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchase_invoices.id'], name=op.f('fk_purchase_items_purchase_id_purchase_invoices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_items'))
    )
    with op.batch_alter_table('purchase_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_items_purchase_id'), ['purchase_id'], unique=False)

    op.create_table('stock_count_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('count_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('system_qty', sa.Float(), nullable=False),
    sa.Column('counted_qty', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['count_id'], ['stock_counts.id'], name=op.f('fk_stock_count_lines_count_id_stock_counts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_stock_count_lines_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_count_lines')),
    sa.UniqueConstraint('count_id', 'product_id', name=op.f('uq_stock_count_lines_count_id'))
    )
    with op.batch_alter_table('stock_count_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_count_lines_count_id'), ['count_id'], unique=False)

    op.create_table('stock_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_stock_levels_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_stock_levels_warehouse_id_warehouses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_levels')),
    sa.UniqueConstraint('product_id', 'warehouse_id', name=op.f('uq_stock_levels_product_id'))
    )
    with op.batch_alter_table('stock_levels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_levels_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_levels_warehouse_id'), ['warehouse_id'], unique=False)

    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('balance_after', sa.Float(), nullable=False),
    sa.Column('ref_type', sa.String(length=32), nullable=False),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=256), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_stock_movements_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_stock_movements_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_stock_movements_warehouse_id_warehouses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_movements'))
    )
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_movements_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_warehouse_id'), ['warehouse_id'], unique=False)

    op.create_table('transfer_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transfer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_transfer_items_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfers.id'], name=op.f('fk_transfer_items_transfer_id_transfers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transfer_items'))
    )
    with op.batch_alter_table('transfer_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transfer_items_transfer_id'), ['transfer_id'], unique=False)

    op.create_table('customer_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_customer_payments_customer_id_customers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_customer_payments_invoice_id_invoices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name=op.f('fk_customer_payments_shift_id_shifts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_customer_payments_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_payments'))
    )
    with op.batch_alter_table('customer_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_payments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_payments_customer_id'), ['customer_id'], unique=False)

    op.create_table('invoice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=256), nullable=False),
    sa.Column('product_code', sa.String(length=64), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('discount', sa.Float(), nullable=False),
    sa.Column('cost_price', sa.Float(), nullable=False),
    sa.Column('line_total', sa.Float(), nullable=False),
    sa.Column('returned_qty', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_invoice_items_invoice_id_invoices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_invoice_items_product_id_products'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_items'))
    )
    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_items_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_items_product_id'), ['product_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_items_product_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_items_invoice_id'))

    op.drop_table('invoice_items')
    with op.batch_alter_table('customer_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_payments_customer_id'))
        batch_op.drop_index(batch_op.f('ix_customer_payments_created_at'))

    op.drop_table('customer_payments')
    with op.batch_alter_table('transfer_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transfer_items_transfer_id'))

    op.drop_table('transfer_items')
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_movements_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_product_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_kind'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_created_at'))

    op.drop_table('stock_movements')
    with op.batch_alter_table('stock_levels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_levels_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_stock_levels_product_id'))

    op.drop_table('stock_levels')
    with op.batch_alter_table('stock_count_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_count_lines_count_id'))

    op.drop_table('stock_count_lines')
    with op.batch_alter_table('purchase_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_items_purchase_id'))

    op.drop_table('purchase_items')
    op.drop_table('promotions')
    with op.batch_alter_table('product_tier_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_tier_prices_product_id'))

    op.drop_table('product_tier_prices')
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_images_product_id'))

    op.drop_table('product_images')
    with op.batch_alter_table('product_field_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_field_values_product_id'))
        batch_op.drop_index(batch_op.f('ix_product_field_values_field_id'))

    op.drop_table('product_field_values')
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_history_product_id'))
        batch_op.drop_index(batch_op.f('ix_price_history_changed_at'))

    op.drop_table('price_history')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_number'))
        batch_op.drop_index(batch_op.f('ix_invoices_kind'))

    op.drop_table('invoices')
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_expense_date'))

    op.drop_table('expenses')
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batches_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_batches_product_id'))
        batch_op.drop_index(batch_op.f('ix_batches_expiry_date'))

    op.drop_table('batches')
    op.drop_table('transfers')
    op.drop_table('sync_log')
    op.drop_table('stock_counts')
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shifts_user_id'))

    op.drop_table('shifts')
    op.drop_table('purchase_invoices')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_parent_id'))
        batch_op.drop_index(batch_op.f('ix_products_name'))
        batch_op.drop_index(batch_op.f('ix_products_code'))
        batch_op.drop_index(batch_op.f('ix_products_category_id'))
        batch_op.drop_index(batch_op.f('ix_products_brand'))
        batch_op.drop_index(batch_op.f('ix_products_barcode'))

    op.drop_table('products')
    with op.batch_alter_table('exchange_rate_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exchange_rate_history_currency_code'))

    op.drop_table('exchange_rate_history')
    with op.batch_alter_table('device_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_device_sessions_jti'))

    op.drop_table('device_sessions')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_phone'))
        batch_op.drop_index(batch_op.f('ix_customers_name'))

    op.drop_table('customers')
    op.drop_table('custom_fields')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    op.drop_table('warehouses')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('suppliers')
    op.drop_table('settings')
    op.drop_table('saved_reports')
    op.drop_table('price_tiers')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_kind'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    op.drop_table('expense_categories')
    op.drop_table('currencies')
    op.drop_table('counters')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_parent_id'))

    op.drop_table('categories')
    op.drop_table('ai_cache')
    # ### end Alembic commands ###
